routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //Route::get('/', 'HomeController@index');
   
});

Route::resource('products', 'ProductController');
Route::resource('costos', 'AddCostosController');
Route::resource('users', 'UserController');
Route::resource('sales', 'SaleController');
Route::resource('repors', 'ReportController');
Route::get('/product', 'ProductController@index');
Route::Get('/meli', 'MeliController@index');
Route::Get('/user', 'UserController@index');
Route::Get('sales', 'SaleController@index');
Route::Get('/orders', 'TokenController@consult_orders');
Route::get('/dashboard', 'TokenController@index')->name('home');
Route::get('/costo', 'AddCostosController@index')->name('costo');
Route::get('/put_costo', 'AddCostosController@store')->name('put_costo');
Route::get('/listar_costos', 'AddCostosController@show')->name('get_costo');
Route::get('/get_id_costo', 'AddCostosController@store')->name('get_ids_costo');
Route::get('/customer', 'CustomerController@create')->name('customer');
Route::get('/put_customer', 'CustomerController@store')->name('put_customer');
Route::get('/get_customer', 'CustomerController@index')->name('get_customer');
Route::get('/get_id_customer', 'CustomerController@show')->name('get_id_customer');
Route::get('/report', 'ReportController@index')->name('get_report');
Route::get('/get_report_sales', 'ReportController@store')->name('get_report_sales');
Route::Get('/invoice', 'InvoiceController@index')->name('invoices');
Route::Get('/detail_invoice', 'DetailInvoiceController@index')->name('detail_invoices');

resources/views/producto/add_producto.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-9 col-md-offset-1">
                                        <form action="{{route('products.store')}}" method="post" autocomplete="on">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <div class="card">
                                            <div class="card-header">
                                                <h4 class="card-title">Agregar Producto
                                                </h4>
                                            </div>
                                            <div class="card-content">
                                                <ul class="nav nav-pills nav-pills-warning">
                                                    <li class="active">
                                                        <a href="#pill1" data-toggle="tab">Factura</a>
                                                    </li>
                                                    
                                                </ul>
                                                <div class="tab-content">
                                                    <div class="tab-pane active" id="pill1">
                                                        <div class="row">
                                                            <label class="col-sm-2 label-on-left">Descripcion</label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input name="description" required="required" type="text" class="form-control" value >
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                            <label class="col-sm-2 label-on-left">Codigo</label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input name="code_product" required="required" type="text" class="form-control" value>
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                         <label class="col-sm-2 label-on-left">Cantidad</label>
                                                         <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input name="cantidad" required="required" type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                        <label class="col-sm-2 label-on-left">Precio Unitario C/IVA</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input name="precio_iva" required="required" type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <label class="col-sm-2 label-on-left">Precio Unitario S/IVA</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input name="precio_s_iva" required="required" type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                        <label class="col-sm-2 label-on-left">Costo Unitario</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input name="costo_unit" required="required" type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="card-content footer text-center">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <input class="btn" type="submit" value="Guardar" /> 
                                                            </div>
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <a href="listar_producto.html" class="btn">Cancelar</a>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </form>
                                </div>
                                
                            </div>

                        </div>

@endsection

resources/views/producto/edit_producto.blade.php
@extends('layouts.app')

@section('content')

                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-9 col-md-offset-1">
                                        <div class="card">
                                            <div class="card-header">
                                                <h4 class="card-title">Editar Producto
                                                </h4>
                                            </div>
                                            <div class="card-content">
                                                <ul class="nav nav-pills nav-pills-warning">
                                                    <li class="active">
                                                        <a href="#pill1" data-toggle="tab">Factura</a>
                                                    </li>
                                                    
                                                </ul>
                                                <div class="tab-content">
                                                    <div class="tab-pane active" id="pill1">
                                                        <div class="row">
                                                            <label class="col-sm-2 label-on-left">Descripcion</label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input type="text" class="form-control" value>
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                            <label class="col-sm-2 label-on-left">Codigo</label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input type="text" class="form-control" value>
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                         <label class="col-sm-2 label-on-left">Cantidad</label>
                                                         <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                        <label class="col-sm-2 label-on-left">Precio Unitario C/IVA</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <label class="col-sm-2 label-on-left">Precio Unitario S/IVA</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                        <label class="col-sm-2 label-on-left">Costo Unitario</label>
                                                        <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input type="text" class="form-control" value>
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="card-content footer text-center">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <a href="" class="btn">Aceptar</a>
                                                            </div>
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <a href="listar_producto.html" class="btn">Cancelar</a>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>

                        </div>

@endsection

resources/views/producto/ver_producto.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
                            <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                    <div class="card">
                                        <div class="card-header card-header-icon" data-background-color="rose">
                                            <i class="material-icons">view_list</i>
                                        </div>
                                        <div class="card-content">
                                            <h4 class="card-title">Producto-
                                                <small class="category">Información Detallada</small>
                                            </h4>
                                            <form>
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Descripción</label>
                                                            <input type="text" class="form-control" disabled>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Cantidad</label>
                                                            <input disabled type="text" class="form-control">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Código</label>
                                                            <input disabled type="text" class="form-control">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Precio Unitario C/IVA</label>
                                                            <input type="text" class="form-control" disabled>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Precio Unitario S/IVA</label>
                                                            <input disabled type="text" class="form-control">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Costo Unitario</label>
                                                            <input disabled type="email" class="form-control">
                                                        </div>
                                                    </div>
                                                </div>
                                                
                                               

                                                <a href="listar_producto.html" class="btn pull-right">Volver</a>
                                                <div class="clearfix"></div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

@endsection