routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //Route::get('/', 'HomeController@index');
   
});

Route::resource('products', 'ProductController');
Route::resource('costos', 'AddCostosController');
Route::resource('users', 'UserController');
Route::resource('sales', 'SaleController');
Route::resource('repors', 'ReportController');
Route::get('/product', 'ProductController@index');
Route::Get('/meli', 'MeliController@index');
Route::Get('/user', 'UserController@index');
Route::Get('sales', 'SaleController@index');
Route::Get('/orders', 'TokenController@consult_orders');
Route::get('/dashboard', 'TokenController@index')->name('home');
Route::get('/costo', 'AddCostosController@index')->name('costo');
Route::get('/put_costo', 'AddCostosController@store')->name('put_costo');
Route::get('/listar_costos', 'AddCostosController@show')->name('get_costo');
Route::get('/get_id_costo', 'AddCostosController@store')->name('get_ids_costo');
Route::get('/customer', 'CustomerController@create')->name('customer');
Route::get('/put_customer', 'CustomerController@store')->name('put_customer');
Route::get('/get_customer', 'CustomerController@index')->name('get_customer');
Route::get('/get_id_customer', 'CustomerController@show')->name('get_id_customer');
Route::get('/report', 'ReportController@index')->name('get_report');
Route::get('/get_report_sales', 'ReportController@store')->name('get_report_sales');
Route::Get('/invoice', 'InvoiceController@index')->name('invoices');
Route::Get('/detail_invoice', 'DetailInvoiceController@index')->name('detail_invoices');

resources/views/login/edit_user.blade.php
@extends('layouts.app')
@section('content')

                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-4 col-sm-6 col-md-offset-3 col-sm-offset-3">
                                                <form action="{{route('users.update', $user['id'])}}" method="POST" autocomplete="on">
                                                    <input type="hidden" name="_method" value="PATCH">
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                                                    <div class="card card-login card-hidden">
                                                        <div class="card-header text-center" data-background-color>
                                                            <h4 class="card-title">Editar Usuario</h4>
                                                        </div>
                                                        
                                                        <div class="card-content">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    <i class="material-icons">face</i>
                                                                </span>
                                                                <div class="form-group label-floating">
                                                                    <label class="control-label">Nombre</label>
                                                                    <input type="text" name="name" required="required" class="form-control" value="{{ $user['name'] }}" >
                                                                </div>
                                                            </div>
                                                            
                                                            
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    <i class="material-icons">email</i>
                                                                </span>
                                                                <div class="form-group label-floating">
                                                                    <label class="control-label">Correo</label>
                                                                    <input id="email" name="email" required="required" type="text" placeholder="correo@mail.com" value="{{ $user['email'] }}"/>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="card-content footer text-center">
                                                            <div class="row">
                                                                <div class=" col-xs-12  col-md-12">
                                                                    <div class=" col-md-4 col-md-offset-1">
                                                                        <button type="submit" class="btn">Guardar</button>
                                                                    </div>
                                                                    <div class="col-md-4 col-md-offset-1">
                                                                        <a href="listar_user.html" class="btn">Cancelar</a>
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>

@endsection

resources/views/login/listar_user.blade.php
@extends('layouts.app')
@section('content')

                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div style="padding:15px" class="card-header card-header-icon" data-background-color><a href="agregar.html"  rel="tooltip" title="Agregar"><i class="material-icons">assignment</i></a>
                                        </div>
                                        <div class="card-content">
                                            <h4 class="card-title">Lista De Usuarios</h4>
                                            <div class="toolbar">
                                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                                            </div>
                                            <div class="material-datatables">
                                                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th class="disabled-sorting ">Nombre</th>
                                                            <th class="disabled-sorting ">Correo</th>
                                                            <th class="disabled-sorting text-right">Editar</th>
                                                            <th class="disabled-sorting text-right">Cambiar contraseña</th>
                                                            <th class="disabled-sorting text-right">Eliminar</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach ($users as $user)
                                                        <tr>
                                                            <td>{{ $user->name }}</td>
                                                            <td>{{ $user->email }}</td>
                                                            <td class="td-actions text-right">
                                                                <a href="edit_user.html" type="button" rel="tooltip" class="btn btn-success btn-simple">
                                                                    <i class="material-icons">edit</i>
                                                                </a>
                                                            </td>
                                                            <td class="td-actions text-right">
                                                                <a href="change_pass.html" type="button" rel="tooltip" class="btn btn-success btn-simple">
                                                                    <i class="material-icons">https</i>
                                                                </a>
                                                            </td>
                                                            <td style="width: 10%" class="td-actions text-right">
                                                                <button  onclick="demo.showSwal('warning-message-and-confirmation')" type="button" rel="tooltip" class="btn btn-danger btn-simple">
                                                                <i class="material-icons">close</i>
                                                                </button>
                                                            </td>
                                                        </tr>
                                                        @endforeach                                                        
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <!-- end content-->
                                    </div>
                                    <!--  end card  -->
                                </div>
                                <!-- end col-md-12 -->
                            </div>
                            <!-- end row -->
                        </div

@endsection

resources/views/login/login.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="{{ asset ('img/apple-icon.png') }}" />
        <link rel="icon" type="image/png" href="{{ asset ('img/favicon.png') }}" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Material Dashboard</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
        <!-- Bootstrap core CSS     -->
        <link href="{{ asset ('css/bootstrap.min.css') }}" rel="stylesheet" />
        <!--  Material Dashboard CSS    -->
        <link href="{{ asset ('css/material-dashboard.css') }}" rel="stylesheet" />
        <!--  CSS for Demo Purpose, don't include it in your project     -->
        <link href="{{ asset ('css/demo.css') }}" rel="stylesheet" />
        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    </head>
    <body>
        <div class="wrapper wrapper-full-page">
            <div class="full-page login-page" filter-color="black" data-image="{{ asset ('img/sidebar-4.jpg') }}">
                <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
                <div class="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                                <form method="#" action="#">
                                    <div class="card card-login card-hidden">
                                        <div class="card-header text-center" data-background-color>
                                            <h4 class="card-title">Login</h4>
                                        </div>
                                        
                                        <div class="card-content">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="material-icons">face</i>
                                                </span>
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Usuario</label>
                                                    <input type="text" class="form-control">
                                                </div>
                                            </div>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="material-icons">lock_outline</i>
                                                </span>
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Contraseñas</label>
                                                    <input type="password" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-content footer text-center" aling="center">
                                            <button type="submit" class="btn">Entrar</button>
                                        </div>
                                        <div class="footer text-center ">
                                            <a href="reset-pass.html" class="btn btn-simple btn-wd btn-lg olvido_pass">¿Olvidó la contraseña?</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <footer class="footer">
                    <div class="container">
                        
                    </div>
                </footer>
            </div>
        </div>
    </body>
    <!--   Core JS Files   -->
    <script src="{{ asset ('js/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset ('js/jquery-ui.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset ('js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset ('js/material.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset ('js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
    <!-- Forms Validations Plugin -->
    <script src="{{ asset ('js/jquery.validate.min.js') }}"></script>
    <!--  Plugin for Date Time Picker and Full Calendar Plugin-->
    <script src="{{ asset ('js/moment.min.js') }}"></script>
    <!--  Charts Plugin -->
    <script src="{{ asset ('js/chartist.min.js') }}"></script>
    <!--  Plugin for the Wizard -->
    <script src="{{ asset ('js/jquery.bootstrap-wizard.js') }}"></script>
    <!--  Notifications Plugin    -->
    <script src="{{ asset ('js/bootstrap-notify.js') }}"></script>
    <!-- DateTimePicker Plugin -->
    <script src="{{ asset ('js/bootstrap-datetimepicker.js') }}"></script>
    <!-- Vector Map plugin -->
    <script src="{{ asset ('js/jquery-jvectormap.js') }}"></script>
    <!-- Sliders Plugin -->
    <script src="{{ asset ('js/nouislider.min.js') }}"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <!-- Select Plugin -->
    <script src="{{ asset ('js/jquery.select-bootstrap.js') }}"></script>
    <!--  DataTables.net Plugin    -->
    <script src="{{ asset ('js/jquery.datatables.js') }}"></script>
    <!-- Sweet Alert 2 plugin -->
    <script src="{{ asset ('js/sweetalert2.js') }}"></script>
    <!--    Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="{{ asset ('js/jasny-bootstrap.min.js') }}"></script>
    <!--  Full Calendar Plugin    -->
    <script src="{{ asset ('js/fullcalendar.min.js') }}"></script>
    <!-- TagsInput Plugin -->
    <script src="{{ asset ('js/jquery.tagsinput.js') }}"></script>
    <!-- Material Dashboard javascript methods -->
    <script src="{{ asset ('js/material-dashboard.js') }}"></script>
    <!-- Material Dashboard DEMO methods, don't include it in your project! -->
    <script src="{{ asset ('js/demo.js') }}"></script>
    <script type="text/javascript">
    $().ready(function() {
    demo.checkFullPageBackgroundImage();
    setTimeout(function() {
    // after 1000 ms we add the class animated to the login/register card
    $('.card').removeClass('card-hidden');
    }, 700)
    });
    </script>
</html>

resources/views/login/registro.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="{{ asset ('img/apple-icon.png') }}" />
        <link rel="icon" type="image/png" href="{{ asset ('img/favicon.png') }}" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Material Dashboard</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
        <!-- Bootstrap core CSS     -->
        <link href="{{ asset ('css/bootstrap.min.css') }}" rel="stylesheet" />
        <!--  Material Dashboard CSS    -->
        <link href="{{ asset ('css/material-dashboard.css') }}" rel="stylesheet" />
        <!--  CSS for Demo Purpose, don't include it in your project     -->
        <link href="{{ asset ('css/demo.css') }}" rel="stylesheet" />
        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    </head>
    <body>
        <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                </div>
                
            </nav>
            <div class="wrapper wrapper-full-page">
                <div class="full-page login-page" filter-color="black" data-image="{{ asset ('img/sidebar-4.jpg') }}">
                    <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
                    <div class="content">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                                    <form action="{{route('users.store')}}" method="post" autocomplete="on">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <div class="card card-login card-hidden">
                                            <div class="card-header text-center" data-background-color>
                                                <h4 class="card-title">Registro</h4>
                                            </div>                                            
                                            <div class="card-content">
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="material-icons">face</i>
                                                    </span>
                                                    <div class="form-group label-floating">
                                                        <label class="control-label">Nombre</label>
                                                        <input type="text" name="name" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="material-icons">email</i>
                                                    </span>
                                                    <div class="form-group label-floating">
                                                        <label class="control-label">Correo</label>
                                                        <input type="email" name="email" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                    <div class="form-group label-floating">
                                                        <label class="control-label">Contraseña</label>
                                                        <input type="password" name="password" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                    <div class="form-group label-floating">
                                                        <label class="control-label">Repetir Contraseña</label>
                                                        <input type="password" name="password" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-content footer text-center">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="col-md-4 col-md-offset-1">
                                                            <button type="submit" class="btn">Guardar</button>
                                                        </div>
                                                        <div class="col-md-4 col-md-offset-1">
                                                            <button type="submit" class="btn">Cancelar</button>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <footer class="footer">
                            <div class="container">
                                
                            </div>
                        </footer>
                    </div>
                </div>
            </body>
            <!--   Core JS Files   -->
            <script src="{{ asset ('js/jquery-3.1.1.min.js') }}" type="text/javascript"></script>
            <script src="{{ asset ('js/jquery-ui.min.js') }}" type="text/javascript"></script>
            <script src="{{ asset ('js/bootstrap.min.js') }}" type="text/javascript"></script>
            <script src="{{ asset ('js/material.min.js') }}" type="text/javascript"></script>
            <script src="{{ asset ('js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
            <!-- Forms Validations Plugin -->
            <script src="{{ asset ('js/jquery.validate.min.js') }}"></script>
            <!--  Plugin for Date Time Picker and Full Calendar Plugin-->
            <script src="{{ asset ('js/moment.min.js') }}"></script>
            <!--  Charts Plugin -->
            <script src="{{ asset ('js/chartist.min.js') }}"></script>
            <!--  Plugin for the Wizard -->
            <script src="{{ asset ('js/jquery.bootstrap-wizard.js') }}"></script>
            <!--  Notifications Plugin    -->
            <script src="{{ asset ('js/bootstrap-notify.js') }}"></script>
            <!-- DateTimePicker Plugin -->
            <script src="{{ asset ('js/bootstrap-datetimepicker.js') }}"></script>
            <!-- Vector Map plugin -->
            <script src="{{ asset ('js/jquery-jvectormap.js') }}"></script>
            <!-- Sliders Plugin -->
            <script src="{{ asset ('js/nouislider.min.js') }}"></script>
            <!--  Google Maps Plugin    -->
            <script src="https://maps.googleapis.com/maps/api/js"></script>
            <!-- Select Plugin -->
            <script src="{{ asset ('js/jquery.select-bootstrap.js') }}"></script>
            <!--  DataTables.net Plugin    -->
            <script src="{{ asset ('js/jquery.datatables.js') }}"></script>
            <!-- Sweet Alert 2 plugin -->
            <script src="{{ asset ('js/sweetalert2.js') }}"></script>
            <!--    Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
            <script src="{{ asset ('js/jasny-bootstrap.min.js') }}"></script>
            <!--  Full Calendar Plugin    -->
            <script src="{{ asset ('js/fullcalendar.min.js') }}"></script>
            <!-- TagsInput Plugin -->
            <script src="{{ asset ('js/jquery.tagsinput.js') }}"></script>
            <!-- Material Dashboard javascript methods -->
            <script src="{{ asset ('js/material-dashboard.js') }}"></script>
            <!-- Material Dashboard DEMO methods, don't include it in your project! -->
            <script src="{{ asset ('js/demo.js') }}"></script>
            <script type="text/javascript">
            $().ready(function() {
            demo.checkFullPageBackgroundImage();
            setTimeout(function() {
            // after 1000 ms we add the class animated to the login/register card
            $('.card').removeClass('card-hidden');
            }, 700)
            });
            </script>
        </html>

resources/views/login/reset_pass.blade.php
@extends('layouts.app')
@section('content')

                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                            <form method="#" action="#">
                                <div class="card card-login card-hidden">
                                    <div class="card-header text-center" data-background-color>
                                        <h4 class="card-title">Restaurar Contraseña</h4>
                                    </div>
                                    
                                    <div class="card-content">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">email</i>
                                            </span>
                                            <div class="form-group label-floating">
                                                <label class="control-label">Email address</label>
                                                <input type="email" class="form-control">
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <div class="card-content footer text-center" aling="center">
                                    <button type="submit" class="btn">Enviar</button>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>

@endsection