routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //Route::get('/', 'HomeController@index');
   
});

Route::resource('products', 'ProductController');
Route::resource('costos', 'AddCostosController');
Route::resource('users', 'UserController');
Route::resource('sales', 'SaleController');
Route::resource('repors', 'ReportController');
Route::get('/product', 'ProductController@index');
Route::Get('/meli', 'MeliController@index');
Route::Get('/user', 'UserController@index');
Route::Get('sales', 'SaleController@index');
Route::Get('/orders', 'TokenController@consult_orders');
Route::get('/dashboard', 'TokenController@index')->name('home');
Route::get('/costo', 'AddCostosController@index')->name('costo');
Route::get('/put_costo', 'AddCostosController@store')->name('put_costo');
Route::get('/listar_costos', 'AddCostosController@show')->name('get_costo');
Route::get('/get_id_costo', 'AddCostosController@store')->name('get_ids_costo');
Route::get('/customer', 'CustomerController@create')->name('customer');
Route::get('/put_customer', 'CustomerController@store')->name('put_customer');
Route::get('/get_customer', 'CustomerController@index')->name('get_customer');
Route::get('/get_id_customer', 'CustomerController@show')->name('get_id_customer');
Route::get('/report', 'ReportController@index')->name('get_report');
Route::get('/get_report_sales', 'ReportController@store')->name('get_report_sales');
Route::Get('/invoice', 'InvoiceController@index')->name('invoices');
Route::Get('/detail_invoice', 'DetailInvoiceController@index')->name('detail_invoices');

app/Costo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Costo extends Model
{
    protected $fillable = [
        'code', 'description', 'venta',
    ];
}

resources/views/costo/add_costo.blade.php
@extends('layouts.app')

@section('content')
   
   									<div class="container-fluid">
                                        <div class="row">
                                            <div class="col-md-9 col-md-offset-1">
                                                <form action="{{route('costos.store')}}" method="post" autocomplete="on">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <div class="card">
                                                    <div class="card-header">
                                                        <h4 class="card-title">Agregar Costo
                                                        </h4>
                                                    </div>
                                                    <div class="card-content">
                                                        <ul class="nav nav-pills nav-pills-warning">
                                                            <li class="active">
                                                                <a href="#pill1" data-toggle="tab">Información Detallada</a>
                                                            </li>
                                                            
                                                        </ul>
                                                        <div class="tab-content">
                                                            <div class="tab-pane active" id="pill1">
                                                                <div class="row">
                                                                    <label class="col-sm-2 label-on-left">Código</label>
                                                                    <div class="col-sm-4">
                                                                        <div class="form-group label-floating is-empty">
                                                                            <label class="control-label"></label>
                                                                            <input name="code" required="required" type="text" class="form-control" value>
                                                                            <span class="help-block">*Requerido</span>
                                                                        </div>
                                                                    </div>
                                                                    <label class="col-sm-2 label-on-left">Descripción

                                                                    </label>
                                                                    <div class="col-sm-4">
                                                                        <div class="form-group label-floating is-empty">
                                                                            <label class="control-label"></label>
                                                                            <input name="description" required="required" type="text" class="form-control" value>
                                                                            <span class="help-block">*Requerido</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                   <label class="col-sm-2 label-on-left">Venta</label>
                                                                   <div class="col-sm-4">
                                                                    <div class="form-group label-floating is-empty">
                                                                        <label class="control-label"></label>
                                                                        <input name="venta" required="required" type="text" class="form-control" value>
                                                                        <span class="help-block">*Requerido</span>
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>
                                                            
                                                            <div class="card-content footer text-center">
                                                                <div class="row">
                                                                    <div class="col-md-12">
                                                                        <div class="col-md-4 col-md-offset-1">
                                                                            <input class="btn" type="submit" value="Guardar" /> 
                                                                        </div>
                                                                        <div class="col-md-4 col-md-offset-1">
                                                                            <a href="listar_costo.html" class="btn">Cancelar</a>
                                                                        </div>
                                                                    </div>
                                                                    
                                                                </div>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            </form>                                            
                                        </div>

                                    </div>
    
@endsection

resources/views/costo/edit_costo.blade.php
@extends('layouts.app')

@section('content')


							<div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-9 col-md-offset-1">
                                        <form action="{{route('costo.update', $costo['id'])}}" method="POST" autocomplete="on">
                                        <div class="card">
                                            <div class="card-header">
                                                <h4 class="card-title">Editar Costo
                                                </h4>
                                            </div>
                                            <div class="card-content">
                                                <ul class="nav nav-pills nav-pills-warning">
                                                    <li class="active">
                                                        <a href="#pill1" data-toggle="tab">Información Detallada</a>
                                                    </li>                                                    
                                                </ul>
                                                <div class="tab-content">
                                                    <div class="tab-pane active" id="pill1">
                                                        <div class="row">
                                                            <label class="col-sm-2 label-on-left">Código</label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input name="code" required="required" value="$costo['code']" placeholder="Codigo" type="text" class="form-control" value>
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                            <label class="col-sm-2 label-on-left">Descripción

                                                            </label>
                                                            <div class="col-sm-4">
                                                                <div class="form-group label-floating is-empty">
                                                                    <label class="control-label"></label>
                                                                    <input name="description" required="required" placeholder="Descripcion" type="text" class="form-control" value="$costo['description']">
                                                                    <span class="help-block">*Requerido</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                         <label class="col-sm-2 label-on-left">Venta</label>
                                                         <div class="col-sm-4">
                                                            <div class="form-group label-floating is-empty">
                                                                <label class="control-label"></label>
                                                                <input name="venta" placeholder="Venta" required="required" type="text" class="form-control" value="$costo['venta']">
                                                                <span class="help-block">*Requerido</span>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                    
                                                <div class="card-content footer text-center">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <a href="" class="btn">Aceptar</a>
                                                            </div>
                                                            <div class="col-md-4 col-md-offset-1">
                                                                <a href="listar_costo.html" class="btn">Cancelar</a>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                                
                            </div>

                        </div>


@endsection

resources/views/costo/listar_costo.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div style="padding:15px" class="card-header card-header-icon" data-background-color><a href="agregar_costo.html"  rel="tooltip" title="Agregar"><i class="material-icons">image</i></a>
                                    </div>
                                    <div class="card-content">
                                        <h4 class="card-title">Lista De Costo</h4>
                                        <div class="toolbar">
                                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                                        </div>
                                        <div class="material-datatables">
                                            <table id="datatables" class="table table-striped table-no-bordered table-hover table-responsive" cellspacing="0" width="100%" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th class="disabled-sorting ">Código</th>
                                                        <th  class="disabled-sorting ">Producto</th>
                                                        <th class="disabled-sorting ">Costo</th>
                                                        <th class="disabled-sorting text-right">Editar</th>
                                                        <th class="disabled-sorting text-right">Ver Detalles</th>
                                                        <th class="disabled-sorting text-right">Eliminar</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                    @forelse ($costos as $costo)                                                    
                                                    <tr>
                                                        <td>{{$costo['code']}}</td>
                                                        <td>{{ $costo['description'] }}</td>
                                                        <td>{{ $costo['venta']}}</td>
                                                        <td style="width: 10%" class="td-actions text-right">
                                                        <a href="edit_costo.html" type="button" rel="tooltip" class="btn btn-success btn-simple">
                                                            <i class="material-icons">edit</i>
                                                        </a>
                                                            
                                                        </td>
                                                        <td style="width: 10%" class="td-actions text-right">
                                                            <a href="ver_costo.html" type="button" rel="tooltip" class="btn btn-success btn-simple">
                                                                <i class="material-icons"><i class="material-icons">remove_red_eye</i></i>
                                                            </a>
                                                        </td>
                                                        <td class="td-actions text-right">
                                                            <button  onclick="demo.showSwal('warning-message-and-confirmation')" type="button" rel="tooltip" class="btn btn-danger btn-simple">
                                                            <i class="material-icons">close</i>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                    @empty
                                                     <tr><td colspan="11">No existen registros</td></tr>
                                                    @endforelse
                                                    
                                                    
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end content-->
                                </div>
                                <!--  end card  -->
                            </div>
                            <!-- end col-md-12 -->
                        </div>
                        <!-- end row -->
                    </div>

@endsection

resources/views/costo/ver_costo.blade.php
@extends('layouts.app')

@section('content')
    
    <div class="container-fluid">
                            <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                    <div class="card">
                                        <div class="card-header card-header-icon" data-background-color="rose">
                                            <i class="material-icons">image</i>
                                        </div>
                                        <div class="card-content">
                                            <h4 class="card-title">Costo-
                                                <small class="category">Información Detallada</small>
                                            </h4>
                                            <form>
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Código</label>
                                                            <input type="text" class="form-control" disabled>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Descripción</label>
                                                            <input disabled type="text" class="form-control">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="form-group label-floating">
                                                            <label class="control-label">Venta</label>
                                                            <input disabled type="text" class="form-control">
                                                        </div>
                                                    </div>
                                                </div>
                                                
                                                
                                               

                                                <a href="listar_costo.html" class="btn pull-right">Volver</a>
                                                <div class="clearfix"></div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

@endsection